version: '3'
services:
  db:
    image: "postgres:latest"
    container_name: local-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fastcampus_db
    volumes:
      - /Users/teukufuadmaulana/setup/valumes:/var/lib/postgresql/data
